# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-06 12:35
from __future__ import unicode_literals

from django.db import migrations, models

def permissions_forwards(apps, schema_editor):
	from django.contrib.contenttypes.models import ContentType

	Group = apps.get_model('auth', 'Group')
	Permission = apps.get_model('auth', 'Permission')
	
	perm = Permission.objects.get(
		codename = 'add_proyecto',
		content_type__app_label = 'manpycommands')
		
	content_type_group = ContentType.objects.get_for_model(Group)
	content_type_perm = ContentType.objects.get_for_model(Permission)
	
	supergeologo = Group.objects.create(name='Supergeologo')
	geologo = Group.objects.create(name='Geologo')

	supergeologo.permissions.add(perm)	

class Migration(migrations.Migration):
    dependencies = [
    	('manpycommands', '0001_proyecto')
    ]

    operations = [
        migrations.RunPython(permissions_forwards),
        
    ]
